### PR TITLE
fix(addon provider): add missing fields for addon providers endpoint

### LINKED ISSUE #268: [Addon Providers] Add missing fields for addon providers endpoint
Currently we manage only `name`, `logo_url` and `id`.

But the api returns much more fields.

### PR DESCRIPTION
**Pull request by QuentinEscudierScalingo**
The Structure Plan and Addon Provider has changed.
Pricing and Category structures have been had.

Fix #268

### CODE REVIEW

File: addons_providers.go [hunk 1]
```diff
@@ -15,24 +15,49 @@ type AddonProvidersService interface {
...
 type AddonProvider struct {
-	ID      string `json:"id"`
-	LogoURL string `json:"logo_url"`
-	Name    string `json:"name"`
+	ID               string    `json:"id"`
+	LogoURL          string    `json:"logo_url"`
+	Name             string    `json:"name"`
+	ShortDescription string    `json:"short_description"`
+	Description      string    `json:"description"`
+	Category         *Category `json:"category"`
```
Comment (EtienneM) [inline addons_providers.go:56]: question: is there a good reason to use a pointer here? If not, let's not use a pointer
```suggestion
	Category         Category `json:"category"`
```

File: addons_providers.go [hunk 2]
```diff
@@ -15,24 +15,49 @@ type AddonProvidersService interface {
...
+	ProviderName     string    `json:"provider_name"`
+	ProviderURL      string    `json:"provider_url"`
+	HDSAvailable     bool      `json:"hds_available"`
+	Plans            []*Plan   `json:"plans"`
```
Comment (EtienneM) [inline addons_providers.go:60]: question: is there a good reason to use a pointer here? If not, let's not use a pointer
```suggestion
	Plans            []Plan   `json:"plans"`
```

**Review by EtienneM — COMMENTED** [review]
Just a question, otherwise LGTM

**Review by EtienneM — APPROVED** [review]

**Review by EtienneM — CHANGES_REQUESTED** [review]
You forgot to update the CHANGELOG.md file

**Review by EtienneM — APPROVED** [review]
