### PR TITLE
fix(events): app run event wording

### LINKED ISSUE #326: App run event wording is wrongly formatted
```
 emichon@biniou  ~/Documents/Scalingo  scalingo --app biniou timeline
[...]
* Wed Mar 29 2023 15:42:11 - Run             - bashone-off container with command '' <etiennem (etienne@scalingo.com)>
[...]
```

### PR DESCRIPTION
**Pull request by EtienneM**
I also took the opportunity to fix all linter offenses.

Fix #326

- [x] Add a [changelog entry](https://changelog.scalingo.com/)

### CODE REVIEW

File: events_structs.go [hunk 1]
```diff
@@ -39,11 +42,14 @@ func (ev *Event) When() string {
 }
 
 func (ev *Event) Who() string {
+	if ev.User.Email == "deploy@scalingo.com" {
+		return "Scalingo Operator"
+	}
```
Comment (EtienneM) [inline events_structs.go:47]: @Soulou I updated the `Who` method to match what is asked in the related issue. But not that it also impacts other event types. For instance in case of a crash or an alert. Is it OK for you?

File: events_structs.go [hunk 2]
```diff
@@ -39,11 +42,14 @@ func (ev *Event) When() string {
...
 	return fmt.Sprintf("%s (%s)", ev.User.Username, ev.User.Email)
 }
 
 func (ev *Event) PrintableType() string {
-	return strings.Title(strings.Replace(string(ev.Type), "_", " ", -1))
+	return cases.Title(language.English).String(strings.Replace(string(ev.Type), "_", " ", -1))
```
Comment (EtienneM) [inline events_structs.go:52]: `strings.Title` is deprecated, hence this change.

File: events_structs.go (hunk 1 above)
Comment (Soulou) [reply events_structs.go:47]: Could we keep something more generic like Scalingo Platform? (It seems to me it's already what is in the event no?)

It's weird to say an operator crashes a container

File: events_structs.go [hunk 3]
```diff
@@ -289,7 +296,17 @@ func (ev *EventRunType) String() string {
...
+
+	if ev.isEventRunFromOperator() {
+		// The command executed is not available to end user if it's executed by a Scalingo operator
+		return fmt.Sprintf("%sone-off container for maintenance/support purposes", detached)
+	}
+
+	return fmt.Sprintf("%sone-off container with command '%s'", detached, ev.TypeData.Command)
+}
+
+func (ev *EventRunType) isEventRunFromOperator() bool {
```
Comment (Soulou) [inline events_structs.go:308]: Isn't it more if the comande is run by the generic user?

Comment (EtienneM) [reply events_structs.go:308]: What do you mean by "generic user"?

File: events_structs.go (hunk 1 above)
Comment (EtienneM) [reply events_structs.go:47]: The current output is `<scalingo-platform (deploy@scalingo.com)>`. I wanted to follow what is asked on the related issu but I agree that this feels a bit odd. Or maybe I could try to modify it only for the run event?

**Comment by EtienneM** [comment]
With commit , only the run event has a custom user name. So the output is:

```
* Mon Sep 18 2023 15:06:42 - Run        - one-off container for maintenance/support purposes <Scalingo Operator>
* Mon Sep 18 2023 15:05:07 - Deployment - deployment of 949de4437933f3ceca7f7e51a98e2af7652a8dde (success) <scalingo-platform (deploy@scalingo.com)>
```

We can see `Scalingo Operator` for a run event by a Scalingo operator, and still the same output for another scalingo-deploy event.

**Comment by EtienneM** [comment]
With commit 4782dab, only the run event has a custom user name. So the output is:

```
* Mon Sep 18 2023 15:06:42 - Run        - one-off container for maintenance/support purposes <Scalingo Operator>
* Mon Sep 18 2023 15:05:07 - Deployment - deployment of 949de4437933f3ceca7f7e51a98e2af7652a8dde (success) <scalingo-platform (deploy@scalingo.com)>
```

We can see `Scalingo Operator` for a run event by a Scalingo operator, and still the same output for another scalingo-deploy event.

File: events_structs.go (hunk 1 above)
Comment (Soulou) [reply events_structs.go]: For the run event I agree, for these rest it's misleading..

Comment (EtienneM) [reply events_structs.go]: OK that's what is included in the commit 4782dab

**Review by Soulou — APPROVED** [review]

**Comment by EtienneM** [comment]
@curzolapierre I let you assigned as reviewer. I wanted Soulou's thoughts about the wording but I want your review on the code part :)

File: events_structs_test.go [hunk 4]
```diff
@@ -48,6 +48,22 @@ var eventsSpecializeCases = map[string]struct {
 		DetailedEventName:   "*scalingo.EventEditAppType",
 		DetailedEventString: "application settings have been updated, Force HTTPS has been disabled",
 	},
+	"test app run event for a command run by an opeator": {
```
Comment (curzolapierre) [inline events_structs_test.go:51]:
```suggestion
	"test app run event for a command run by an operator": {
```

**Review by curzolapierre — APPROVED** [review]
Thanks for the cleaning :+1: 
Just a typo but otherwise LGTM

**Comment by EtienneM** [comment]
Sorry @curzolapierre, pushing your suggestion dismissed your review..
